name: MegaScrp  # <-- Workflow name

on:
  push:
    branches: [ main ]     # وقتی به شاخه اصلی push میکنی اجرا میشه
  pull_request:
    branches: [ main ]     # وقتی pull request به main میاد اجرا میشه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # نسخه پایتون پروژه

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # اگر requirements نداری میتونی حذفش کنی

    - name: Test with pytest
      run: |
        pytest   # یا هر دستور تست خودت
